import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'

export default function Home() {
  const { data: session, status } = useSession()

  console.log(status);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === 'loading' ? (
        <main className='flex bg-slate-900 min-h-screen text-slate-100 items-center justify-center'>
            <div className='p-5 h-96 w-[30rem] flex flex-col space-y-10 items-center justify-center border-2 rounded-lg border-slate-700'>
              <h1 className='text-lg font-medium uppercase '>loading...</h1>
            </div>
      </main>
      ) : (
        <main className='flex bg-slate-900 min-h-screen text-slate-100 items-center justify-center'>
        {
          session ? (
            <div className='p-5 h-96 w-[30rem] flex flex-col space-y-10 items-center justify-center border-2 rounded-lg border-slate-700'>
              <h1 className='text-base font-medium uppercase '>Logged in as: <span className='text-emerald-400 text-lg'>{session.user.name}</span></h1>
              <button className='bg-red-400 px-5 py-2 rounded-md text-white font-medium' onClick={() => signOut()}>Sign out</button>
            </div>
          ) : (
            <div className='p-5 h-96 w-[30rem] flex flex-col space-y-10 items-center justify-center border-2 rounded-lg border-slate-700'>
              <h1 className='text-lg font-medium uppercase '>Not logged in</h1>
              <button className='bg-emerald-500 px-5 py-2 rounded-md text-white font-medium' onClick={() => signIn()}>Sign in</button>
            </div>
          )
        }
      </main>
      )}
    </div>
  )
}
